services:
  backend:
    build:
      context: ./backend
    command: >
      bash -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn django_setup.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_APP_NAME: ${VITE_APP_NAME}
    ports:
      - "80:80"
    env_file:
      - .env
