version: '3.8'

services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: