# Generated by Django 5.2.1 on 2025-05-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("summary_text", models.TextField()),
                ("sources", models.JSONField(default=list)),
                ("audio_file", models.FileField(upload_to="episodes/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
