# Generated by Django 5.2.1 on 2025-05-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal_club", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
