# Generated by Django 5.2.1 on 2025-05-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal_club", "0003_tag_topic_episodetag_episode_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="episodes", to="journal_club.tag"
            ),
        ),
        migrations.DeleteModel(
            name="EpisodeTag",
        ),
    ]
