# Generated by Django 5.2.1 on 2025-05-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal_club", "0004_episode_tags_delete_episodetag"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="episodes/images/"
            ),
        ),
    ]
