# Generated by Django 5.2.1 on 2025-05-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal_club", "0005_episode_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="topic",
        ),
        migrations.AddField(
            model_name="episode",
            name="topic",
            field=models.ManyToManyField(
                blank=True, related_name="episodes", to="journal_club.topic"
            ),
        ),
    ]
