# Generated by Django 5.2.1 on 2025-05-24 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal_club", "0006_remove_episode_topic_episode_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="topic",
            new_name="topics",
        ),
    ]
