# Generated by Django 5.2.1 on 2025-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal_club", "0009_listeninghistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="listeninghistory",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
