# Generated by Django 5.2.1 on 2025-05-31 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("journal_club", "0010_listeninghistory_duration_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="dislikes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="episode",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="LikeDislike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal_club.episode",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id", "episode")},
            },
        ),
    ]
