# Generated by Django 5.2.1 on 2025-05-31 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_guestuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestuser",
            name="linked_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guest_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
